# -*- coding: utf-8 -*-
"""Whisper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfPxpuNl2TaY5RBWJD2KqsIOhL35Jhue
"""

! pip install git+https://github.com/openai/whisper.git -q

import whisper

model = whisper.load_model("base")

model.device

from IPython.display import Audio
Audio("/content/4-2022-01-21-20-47-52 1 (1).mp3")

from IPython.display import Audio
Audio("/content/4-2022-01-21-20-47-52 1 (1).mp3")

# load audio and pad/trim it to fit 30 seconds
audio = whisper.load_audio("/content/4-2022-01-21-20-47-52 1 (1).mp3")
audio = whisper.pad_or_trim(audio)

# make log-Mel spectrogram and move to the same device as the model
mel = whisper.log_mel_spectrogram(audio).to(model.device)

# detect the spoken language
_, probs = model.detect_language(mel)
print(f"Detected language: {max(probs, key=probs.get)}")

# decode the audio
options = whisper.DecodingOptions()
result = whisper.decode(model, mel, options)

# print the recognized text
print(result.text)